# Generated by Django 3.2.4 on 2021-06-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_artigo_tag_to_thread_thread_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='distintivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='fk_thread',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forum.thread'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='texto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='usuario_to_distintivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_distintivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.distintivo')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.usuario')),
            ],
        ),
    ]
